//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falabella.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public int CLIENTE_ID { get; set; }
        public int PRODUCTO_ID { get; set; }
        public int ASEGURADORA_ID { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string PRIMER_APELLIDO { get; set; }
        public string SEGUNDO_APELLIDO { get; set; }
        public int TIPO_DOCUMENTO { get; set; }
        public string DOCUMENTO { get; set; }
        public string TELEFONO { get; set; }
    
        public virtual ASEGURADORAS ASEGURADORAS { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
        public virtual DOCUMENTOS DOCUMENTOS { get; set; }
    }
}
